# Generated by Django 4.2.26 on 2025-11-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'На рассмотрении'), ('APPROVED', 'Принята'), ('REJECTED', 'Отклонена')], default='PENDING', max_length=10, verbose_name='Статус заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('RECRUITMENT', 'Набор открыт'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершен'), ('ARCHIVED', 'В архиве')], default='RECRUITMENT', max_length=20, verbose_name='Статус')),
                ('max_participants', models.PositiveIntegerField(default=3, verbose_name='Количество мест')),
                ('application_deadline', models.DateField(verbose_name='Срок подачи заявок')),
                ('end_date', models.DateField(verbose_name='Дата завершения проекта')),
                ('milestones', models.TextField(blank=True, help_text='Каждая точка с новой строки.', verbose_name='Контрольные точки (списком)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
    ]
